# Generated by Django 5.0.1 on 2024-02-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=15),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=60),
        ),
    ]
