# Generated by Django 5.0.1 on 2024-02-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Users",
            },
        ),
    ]
