# Generated by Django 5.0 on 2024-02-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="firstName",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="lastName",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
