# Generated by Django 5.0.1 on 2024-02-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("age", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Client",
            },
        ),
    ]
